[package]
name = "wave_to_flac"
version = "0.1.0"
edition = "2024"

[dependencies]
rfd = "0.15.4"
hound = "3.5"
flacenc = "0.5.0"
regex = "1.12.2"
encoding_rs = "0.8.35"
encoding_rs_io = "0.1.7"
image = "0.25.8"  # 画像処理ライブラリ
fs_extra = "1.3.0"
